DROP DATABASE PROYECTO2DB1;
CREATE DATABASE PROYECTO2DB1;
USE PROYECTO2DB1;


CREATE TABLE Docente(
Registro_SIIF INT AUTO_INCREMENT PRIMARY KEY,
DPI INT NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(50) NOT NULL,
Fecha_Nacimiento DATE NOT NULL,
Correo VARCHAR(100) NOT NULL,
Telefono BIGINT NOT NULL,
Direccion VARCHAR(100) NOT NULL,
Fecha_Registro DATETIME NOT NULL
);

CREATE TABLE Carrera(
Id_Carrera INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL
);


CREATE TABLE Estudiante(
Carnet BIGINT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(50) NOT NULL, 
Fecha_Nacimiento DATE NOT NULL,
Correo VARCHAR(100) NOT NULL,
Telefono BIGINT NOT NULL,
Direccion VARCHAR(100) NOT NULL,
DPI INT NOT NULL,
Id_Carrera INT NOT NULL,
Creditos INT NOT NULL DEFAULT 0,
Fecha_Creacion DATETIME,
FOREIGN KEY (Id_Carrera) REFERENCES Carrera(Id_Carrera)
);

CREATE TABLE Transaccion(
Id_Transaccion INT AUTO_INCREMENT PRIMARY KEY,
Tipo VARCHAR(50) NOT NULL,
Descripcion VARCHAR(250) NOT NULL,
Fecha DATETIME NOT NULL
);

CREATE TABLE Curso(
Codigo INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Creditos_Necesarios INT NOT NULL,
Creditos_Otorga INT NOT NULL,
Obligatorio BOOL NOT NULL,
Id_Carrera INT NOT NULL,
FOREIGN KEY (Id_Carrera) REFERENCES Carrera(Id_Carrera) 
);

CREATE TABLE Habilitar_Curso(
No_Habilitacion INT AUTO_INCREMENT PRIMARY KEY,
Ciclo VARCHAR(2) NOT NULL,
Cupo_Maximo INT NOT NULL,
Seccion VARCHAR(1) NOT NULL,
Year_Curso DATE NOT NULL,
Cantidad_Asignados INT NOT NULL DEFAULT 0,
Registro_SIIF INT NOT NULL,
Codigo INT NOT NULL,
FOREIGN KEY (Registro_SIIF) REFERENCES Docente(Registro_SIIF),
FOREIGN KEY (Codigo) REFERENCES Curso(Codigo)  
);

CREATE TABLE Horario(
Id_Horario INT AUTO_INCREMENT PRIMARY KEY,
Dia INT(1) NOT NULL,
Horario VARCHAR(15) NOT NULL,
No_Habilitacion INT NOT NULL,
FOREIGN KEY (No_Habilitacion) REFERENCES Habilitar_Curso(No_Habilitacion) 
);

CREATE TABLE Acta(
Id_Acta INT AUTO_INCREMENT PRIMARY KEY,
Fecha_Hora DATETIME NOT NULL,
Codigo INT NOT NULL,
FOREIGN KEY (Codigo) REFERENCES Curso(Codigo) 
);

CREATE TABLE Asignar_Curso(
Id_Asignacion INT AUTO_INCREMENT PRIMARY KEY,
Estado_Asignacion BOOL NOT NULL,
Carnet BIGINT NOT NULL,
Codigo INT NOT NULL,
FOREIGN KEY (Carnet) REFERENCES Estudiante(Carnet),
FOREIGN KEY (Codigo) REFERENCES Curso(Codigo) 
);

CREATE TABLE Nota(
Id_Nota INT AUTO_INCREMENT PRIMARY KEY,
Nota INT NOT NULL,
Fecha_Ingreso DATETIME NOT NULL,
Id_Asignacion INT NOT NULL,
FOREIGN KEY (Id_Asignacion) REFERENCES Asignar_Curso(Id_Asignacion) 
);
